# Generated by Django 4.0.3 on 2022-10-01 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_benefeciarrequest',
            fields=[
                ('request_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('required_date', models.CharField(max_length=90)),
                ('required_time', models.CharField(max_length=90)),
                ('required_quatity', models.CharField(max_length=90)),
                ('remark', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_benefeciarrequest',
            },
        ),
        migrations.CreateModel(
            name='tbl_beneficiar',
            fields=[
                ('beneficiar_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('contact_person', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('pincode', models.CharField(max_length=90)),
                ('proof', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_donor',
            fields=[
                ('donor_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=90)),
                ('person_in_charge_name', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('alternative_phone', models.CharField(max_length=90)),
                ('pincode', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('proof', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_fooddonation',
            fields=[
                ('donation_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('foodcatagory', models.CharField(max_length=90)),
                ('quantity', models.CharField(max_length=90)),
                ('photo', models.CharField(max_length=90)),
                ('preparation_time', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('required_time', models.CharField(max_length=90)),
                ('remark', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_donor')),
            ],
            options={
                'db_table': 'tbl_fooddonation',
            },
        ),
        migrations.CreateModel(
            name='tbl_idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField()),
                ('did', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('fid', models.IntegerField()),
                ('prid', models.IntegerField()),
                ('rid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('brid', models.IntegerField()),
                ('alid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('catagory', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_volunteers',
            fields=[
                ('volunteer_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('age', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=90)),
                ('natureofjob', models.CharField(max_length=90)),
                ('photo', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('review_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('review', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('beneficiar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_beneficiar')),
            ],
            options={
                'db_table': 'tbl_review',
            },
        ),
        migrations.CreateModel(
            name='tbl_publicrequest',
            fields=[
                ('request_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('contact_person', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('request_food', models.CharField(max_length=90)),
                ('remark', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('quantity', models.CharField(max_length=30)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_fooddonation')),
            ],
            options={
                'db_table': 'tbl_publicrequest',
            },
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('complaint_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('beneficiar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_beneficiar')),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
        migrations.CreateModel(
            name='tbl_beneficiarfoodallot',
            fields=[
                ('allotment_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('request_quatity', models.CharField(max_length=90)),
                ('allotment_quatity', models.CharField(max_length=90)),
                ('remark', models.CharField(max_length=90)),
                ('allotment_date', models.CharField(max_length=90)),
                ('allotment_time', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_fooddonation')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_benefeciarrequest')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_volunteers')),
            ],
            options={
                'db_table': 'tbl_beneficiarfoodallot',
            },
        ),
        migrations.AddField(
            model_name='tbl_benefeciarrequest',
            name='beneficiar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_beneficiar'),
        ),
        migrations.AddField(
            model_name='tbl_benefeciarrequest',
            name='donation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_fooddonation'),
        ),
    ]
