# Generated by Django 4.0.3 on 2022-10-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_fooddonation',
            name='name',
            field=models.CharField(default='ff', max_length=90),
            preserve_default=False,
        ),
    ]
