# Generated by Django 4.0.3 on 2022-10-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tbl_fooddonation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_benefeciarrequest',
            name='donor_id',
            field=models.ForeignKey(default='f', on_delete=django.db.models.deletion.CASCADE, to='app.tbl_donor'),
            preserve_default=False,
        ),
    ]
