# Generated by Django 4.0.5 on 2022-10-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tbl_benefeciarrequest_donor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_fooddonation',
            name='pincode',
            field=models.CharField(default='f', max_length=90),
            preserve_default=False,
        ),
    ]
