# Generated by Django 4.0.3 on 2022-10-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tbl_fooddonation_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_publicreview',
            fields=[
                ('publicreview_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=90)),
                ('review', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_publicreview',
            },
        ),
    ]
