# Generated by Django 4.0.3 on 2022-10-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tbl_publicreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donorcomplaint',
            fields=[
                ('complaint_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('donor_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_donor')),
            ],
            options={
                'db_table': 'tbl_donorcomplaint',
            },
        ),
    ]
