# Generated by Django 4.0.3 on 2022-10-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tbl_donorcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='dcid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_idgen',
            name='drid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
