# Generated by Django 4.0.3 on 2022-10-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tbl_idgen_dcid_tbl_idgen_drid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donorreview',
            fields=[
                ('review_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('review', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_donor')),
            ],
            options={
                'db_table': 'tbl_donorreview',
            },
        ),
    ]
