# Generated by Django 4.0.3 on 2022-10-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tbl_donorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_publicrequest',
            name='donor_id',
            field=models.ForeignKey(default='zufcv', on_delete=django.db.models.deletion.CASCADE, to='app.tbl_donor'),
            preserve_default=False,
        ),
    ]
